on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  golang-version: '1.23'

jobs:
  manifests:
    name: Generate manifests
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.golang-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get install -y git
        sudo apt-get install -y jsonnet
        go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
        go install github.com/brancz/gojsontoyaml@latest

    - uses: actions/checkout@v4
    - name: Build manifests
      run: |
        find . -type f \
          -name "manifests.build" \
          -execdir sh -c \
          'echo "Building manifests in $(pwd): $@" && $@' sh {} +

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: |
          [bot] CI Request: Automated manifests build
        body: |
          ## Summary
          Update manifest files.

          ## Description
          This is an automated update of manifest files for project libraries
          and packages performed from CI.

          Please review the changes before merging this PR.

          Configuration of the workflow is located in
          `.github/workflows/manifests.yaml`.
        branch: actions/manifests
        branch-suffix: short-commit-hash
        delete-branch: true
        commit-message: |
          [bot] automated manifests build
        signoff: true
        sign-commits: true
